"""Rename image_filename to image_url

Revision ID: 857ff6f2b177
Revises: 
Create Date: 2025-02-17 20:09:25.286529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857ff6f2b177'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_image_url', sa.String(length=300), nullable=False))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('image_image_url')

    # ### end Alembic commands ###
